# Generated by Django 4.2.4 on 2023-08-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personality',
            old_name='born',
            new_name='birth',
        ),
    ]
