# Generated by Django 4.2.4 on 2023-08-06 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page2', '0002_rename_born_personality_birth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personality',
            new_name='PersonalInfo',
        ),
    ]
